services:
  php:
    env_file:
      - ${LIBER_WORKSPACE}/infra/conexoes/liberSistemas/APT/.env
      - ${LIBER_WORKSPACE}/infra/conexoes/liberSistemas/APT/.env.odbc

  proxy-db:
    env_file:
      - ${LIBER_WORKSPACE}/infra/conexoes/liberSistemas/APT/.env
